export default {
  ADD_RECIPE: "ADD_RECIPE",
  EDIT_RECIPE: "EDIT_RECIPE",
  UPDATE_RECIPE: "UPDATE_RECIPE",
  DELETE_RECIPE: "DELETE_RECIPE",

  EDIT_INGREDIENT: "EDIT_INGREDIENT",
  SAVE_INGREDIENT: "SAVE_INGREDIENT",
  CANCLE_INGREDIENT: "CANCLE_INGREDIENT",
  DELETE_INGREDIENT: "DELETE_INGREDIENT",
};
